// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnM78lc3SidGWYGrsTwvYubRg8AY6wQyw',
    appId: '1:158649360660:web:c79642aca3e988a5d9e201',
    messagingSenderId: '158649360660',
    projectId: 'alu-launchpad-4825d',
    authDomain: 'alu-launchpad-4825d.firebaseapp.com',
    storageBucket: 'alu-launchpad-4825d.firebasestorage.app',
    measurementId: 'G-MCFF0WW6QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEqdxh_2zg1xRxrLy2nzxxm51epYvdjcw',
    appId: '1:158649360660:android:8eaa0da0b617d5ded9e201',
    messagingSenderId: '158649360660',
    projectId: 'alu-launchpad-4825d',
    storageBucket: 'alu-launchpad-4825d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtjsR6F-dBTXRFnOj81mwsUTa86cCc6z4',
    appId: '1:158649360660:ios:5e5634c8fc327939d9e201',
    messagingSenderId: '158649360660',
    projectId: 'alu-launchpad-4825d',
    storageBucket: 'alu-launchpad-4825d.firebasestorage.app',
    iosBundleId: 'com.example.aluLaunchpad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtjsR6F-dBTXRFnOj81mwsUTa86cCc6z4',
    appId: '1:158649360660:ios:5e5634c8fc327939d9e201',
    messagingSenderId: '158649360660',
    projectId: 'alu-launchpad-4825d',
    storageBucket: 'alu-launchpad-4825d.firebasestorage.app',
    iosBundleId: 'com.example.aluLaunchpad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnM78lc3SidGWYGrsTwvYubRg8AY6wQyw',
    appId: '1:158649360660:web:77c866be11206dedd9e201',
    messagingSenderId: '158649360660',
    projectId: 'alu-launchpad-4825d',
    authDomain: 'alu-launchpad-4825d.firebaseapp.com',
    storageBucket: 'alu-launchpad-4825d.firebasestorage.app',
    measurementId: 'G-K363216MGD',
  );
}
